points:
    key.padding: cy
    zones:
        main:
            rows:
                bottom.row_net: P2
                home.row_net: P0
                top.row_net: P1
            columns:
                pinky:
                    key:
                        col_net: P10
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_top
                        top:
                            led_in: "rgb_{{name}}"
                pinky2:
                    key:
                        col_net: P7
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky2_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky2_top
                        top:
                            led_in: "rgb_{{name}}"
                ring:
                    key:
                        col_net: P6
                        stagger: 4
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_pinky_bottom
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_bottom
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_home
                middle:
                    key:
                        col_net: P5
                        stagger: 2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_middle_top
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_ring_top
                index:
                    key:
                        col_net: P4
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_thumb_home_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_bottom
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_home
                inner:
                    key:
                        col_net: P3
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_home
                        home:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_inner_top
                        top:
                            led_in: "rgb_{{name}}"
                            led_out: rgb_main_index_top
        thumb:
            anchor:
                ref: main_index_bottom
                shift: [-0.5cx, -cy]
            rows.home.row_net: P8
            columns:
                inner.key:
                    col_net: P5
                    led_in: "rgb_{{name}}"
                    led_out: rgb_main_middle_bottom
                    spread: cx
                home.key:
                    col_net: P4
                    led_in: "rgb_{{name}}"
                    led_out: rgb_thumb_inner_home
                    spread: cx + 2
                    rotate: -18
                    stagger: -3.2
                outer.key:
                    col_net: P3
                    led_in: P9
                    led_out: rgb_main_inner_bottom
                    spread: cx
                    rotate: -36
                    stagger: -9.20
                    height: 1.5u
                    shift: [0.25u,0.25u]
    mirror: &mirror
        ref: main_inner_top
        distance: 100
outlines:
    _board_outline:
        -   what: polygon
            fillet: 2
            points:
                -   ref: thumb_outer_home
                    shift: [0.6cx, 0.8cy]
                -   ref: thumb_outer_home
                    shift: [0.6cx, -0.8cy]
                -   ref: thumb_outer_home
                    shift: [-0.4cx, -0.8cy]

                -   ref: thumb_home_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_home_home
                    shift: [-0.4cx, -0.6cy]

                -   ref: thumb_inner_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_inner_home
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_pinky_bottom
                    shift: [1.6cx, -0.6cy]
                -   ref: main_pinky_bottom
                    shift: [0.6cx, -0.6cy]
                -   ref: main_pinky_bottom
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_pinky_top
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_pinky_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_ring_top
                    shift: [-0.5cx, 0.6cy]
                -   ref: main_ring_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_middle_top
                    shift: [-0.4cx, 0.61cy]
                -   ref: main_middle_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_index_top
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_index_top
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_top
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_inner_top
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_top
                    shift: [0.6cx, 0.4cy]
                -   ref: main_inner_top
                    shift: [1.8cx, 0.4cy]

                -   ref: main_inner_bottom
                    shift: [1.8cx, -0.6cy]
    _board2_outline:
        -   what: polygon
            fillet: 2
            points:
                -   ref: mirror_thumb_outer_home
                    shift: [0.6cx, 0.8cy]
                -   ref: mirror_thumb_outer_home
                    shift: [0.6cx, -0.8cy]
                -   ref: mirror_thumb_outer_home
                    shift: [-0.4cx, -0.8cy]

                -   ref: mirror_thumb_home_home
                    shift: [0.4cx, -0.6cy]
                -   ref: mirror_thumb_home_home
                    shift: [-0.4cx, -0.6cy]

                -   ref: mirror_thumb_inner_home
                    shift: [0.4cx, -0.6cy]
                -   ref: mirror_thumb_inner_home
                    shift: [-0.6cx, -0.6cy]

                -   ref: mirror_main_pinky_bottom
                    shift: [1.6cx, -0.6cy]
                -   ref: mirror_main_pinky_bottom
                    shift: [0.6cx, -0.6cy]
                -   ref: mirror_main_pinky_bottom
                    shift: [-0.6cx, -0.6cy]

                -   ref: mirror_main_pinky_top
                    shift: [-0.6cx, 0.6cy]
                -   ref: mirror_main_pinky_top
                    shift: [0.4cx, 0.6cy]

                -   ref: mirror_main_ring_top
                    shift: [-0.5cx, 0.6cy]
                -   ref: mirror_main_ring_top
                    shift: [0.4cx, 0.6cy]

                -   ref: mirror_main_middle_top
                    shift: [-0.4cx, 0.61cy]
                -   ref: mirror_main_middle_top
                    shift: [0.4cx, 0.6cy]

                -   ref: mirror_main_index_top
                    shift: [-0.4cx, 0.6cy]
                -   ref: mirror_main_index_top
                    shift: [0.5cx, 0.6cy]

                -   ref: mirror_main_inner_top
                    shift: [-0.4cx, 0.6cy]
                -   ref: mirror_main_inner_top
                    shift: [0.5cx, 0.6cy]

                -   ref: mirror_main_inner_top
                    shift: [0.6cx, 0.4cy]
                -   ref: mirror_main_inner_top
                    shift: [1.8cx, 0.4cy]

                -   ref: mirror_main_inner_bottom
                    shift: [1.8cx, -0.6cy]
    _keycap_outlines:
        -   what: rectangle
            fillet: 2
            where: [/^main_.*/, /^thumb_.*/]
            size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
    _keycap2_outlines:
        -   what: rectangle
            fillet: 2
            where: [/^mirror_main_.*/, /^mirror_thumb_.*/]
            size: [1cx - 0.5, 1cy - 0.5]
    _space_outline:
        -   what: rectangle
            fillet: 2
            where: [thumb_outer_home, mirror_thumb_outer_home]
            size: [1cx - 0.5, 1.5cy - 0.5]
    preview:
        -   what: outline
            name: _board_outline
            operation: stack
        -   what: outline
            name: _board2_outline
            operation: stack
        -   what: outline
            name: _keycap_outlines
            operation: stack
        -   what: outline
            name: _keycap2_outlines
            operation: stack
        -   what: outline
            name: _space_outline
            operation: stack
cases.corne:
    -   what: outline
        name: _board2_outline
        extrude: 3
    -   what: outline
        name: _board_outline
        extrude: 3
    -   what: outline
        name: _keycap_outlines
        extrude: 6
        operation: add
    -   what: outline
        name: _space_outline
        extrude: 6
        operation: add
pcbs:
    corneL:
        outlines:
            main.outline: _board_outline
            keycaps:
                outline: _keycap_outlines
                layer: Eco1.User
        footprints:
            led:
                what: sk6812mini
                where: [/^main_.*/, /^thumb_.*/]
                adjust:
                    shift: [0, -5]
                params:
                    din: "{{led_in}}"
                    dout: "{{led_out}}"
                    cutout: true
            diode:
                what: sod-123w
                where: [/^main_.*/, /^thumb_.*/]
                params:
                    from: "{{name}}"
                    to: "{{row_net}}"
                adjust:
                    shift: [ -7.6, -1.6 ]
                    rotate: 90
            choc:
                what: choc
                where: [/^main_.*/, /^thumb_.*/]
                params:
                    keycaps: true
                    reverse: false
                    hotswap: true
                    from: "{{col_net}}"
                    to: "{{name}}"
            nice_nano:
                what: nice_nano
                where:
                    ref: main_inner_home
                params:
                    orientation: down
                adjust:
                    shift: [22, 6.5]
                    rotate: -90
            oled:
                what: oled
                params:
                    side: "F"
                    SDA: P2
                    SCL: P3
                where:
                    ref: main_inner_home
                adjust:
                    shift: [16, -12]
                    rotate: 90
            jst-s2b-ph-kl:
                what: jst-s2b-ph-kl
                where:
                    ref: main_inner_bottom
                    shift: [21, -2]
                    rotate: -90
                params:
                    neg: GND
            pcm12:
                what: pcm12
                where:
                    ref: main_inner_bottom
                    shift: [30.5, 3]
                    rotate: 90
                params:
                    from: pos
                    to: RAW
            wuerth-434121025816:
                what: wuerth-434121025816
                where:
                    ref: main_inner_bottom
                    shift: [30, -6]
                    rotate: 90
                params:
                    r1: RST
                    r2: GND


    corneR:
        outlines:
            main.outline: _board2_outline
            keycaps:
                outline: _keycap2_outlines
                layer: Eco1.User
        footprints:
            led:
                what: sk6812mini
                where: [/^mirror_main_.*/, /^mirror_thumb_.*/]
                adjust:
                    shift: [0, -5]
                params:
                    din: "{{led_in}}"
                    dout: "{{led_out}}"
                    cutout: true
            diode:
                what: sod-123w
                where: [/^mirror_main_.*/, /^mirror_thumb_.*/]
                params:
                    from: "{{name}}"
                    to: "{{row_net}}"
                adjust:
                    shift: [ -7.6, -1.6 ]
                    rotate: 90
            choc:
                what: choc
                where: [/^mirror_main_.*/, /^mirror_thumb_.*/]
                params:
                    keycaps: true
                    reverse: false
                    hotswap: true
                    from: "{{col_net}}"
                    to: "{{name}}"
            nice_nano:
                what: nice_nano
                where:
                    ref: mirror_main_inner_home
                params:
                    orientation: down
                adjust:
                    shift: [22, 6.5]
                    rotate: 90
            oled:
                what: oled
                params:
                    side: "F"
                    SDA: P2
                    SCL: P3
                where:
                    ref: mirror_main_inner_home
                adjust:
                    shift: [28, -12]
                    rotate: -90
            jst-s2b-ph-kl:
                what: jst-s2b-ph-kl
                where:
                    ref: mirror_main_inner_bottom
                    shift: [21, -2]
                    rotate: -90
                params:
                    neg: GND
            pcm12:
                what: pcm12
                where:
                    ref: mirror_main_inner_bottom
                    shift: [30.5, 3]
                    rotate: 90
                params:
                    from: pos
                    to: RAW
            wuerth-434121025816:
                what: wuerth-434121025816
                where:
                    ref: mirror_main_inner_bottom
                    shift: [30, -6]
                    rotate: 90
                params:
                    r1: RST
                    r2: GND